version: '3.8'

services:
  youtube-downloader:
    image: ghcr.io/siputzx/youtubedl:latest
    container_name: youtube-downloader
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DOWNLOADS_DIR=/app/downloads
      - AUDIO_DIR=/app/downloads/audio
      - VIDEO_DIR=/app/downloads/video
      - MERGE_DIR=/app/downloads/merge
      - COOKIES_DIR=/app/cookies
      - CACHE_DURATION=18000000
      - MAX_VIDEO_DURATION=10800
      - MAX_AUDIO_DURATION=18000
      - MAX_FILE_SIZE=1073741824
      - POW_DIFFICULTY=2
      - MAX_CONCURRENT=8
      - USE_COOKIES=true
      - PROXY=
      - VALID_APIKEYS=siputzxteam,cepetan
    volumes:
      - ./downloads:/app/downloads
      - ./cookies:/app/cookies
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
